# Generated by Django 4.1.1 on 2022-09-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('production_year', models.IntegerField(default=2022)),
            ],
        ),
    ]
